// this is for the sake of org/best practices
export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE';
export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const DISPLAY_ASSIGNMENT = 'DISPLAY_ASSIGNMENT';
export const DISPLAY_COURSE = 'DISPLAY_COURSE';
export const DISPLAY_STUDENT = 'DISPLAY_STUDENT';
export const GO_HOME = 'GO_HOME';
export const RECEIVE_COURSES_DATA = 'RECEIVE_COURSES_DATA';
export const RECEIVE_COURSES_ERROR = 'RECEIVE_COURSES_ERROR';
export const RETRIEVE_MESSAGES = 'RETRIEVE_MESSAGES';
export const SWITCH_TABS = 'SWITCH_TABS';
export const TOGGLE_DEMO_TYPE = 'TOGGLE_DEMO_TYPE';
